diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=wonsiin01
user.email=answngusdld@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
user.name=wonsiin01
user.email=answngusdld@gmail.com
remote.woniin01.url=https://github.com/wonsiin/wonsiin01.git
remote.woniin01.fetch=+refs/heads/*:refs/remotes/woniin01/*
remote.origin.url=https://github.com/wonsiin/wonsiin01.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
